---
abstract: 'Modules RSRCHBOY uses!'
author:
  - 'Chris Weyl <cweyl@alumni.drew.edu>'
build_requires:
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Test::CheckDeps: 0.010
  Test::More: 0.94
  perl: 5.006
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.133380'
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-BeLike-RSRCHBOY
no_index:
  directory:
    - corpus
    - t
provides:
  Task::BeLike::RSRCHBOY:
    file: lib/Task/BeLike/RSRCHBOY.pm
    version: 0.005
requires:
  App::AltSQL: 0
  App::cpanminus::reporter: 0
  App::cpanoutdated: 0
  App::gh: 0
  CPAN::Mini: 0
  CPAN::Mini::Inject: 0
  Capture::Tiny: 0
  Carp::Always: 0
  Class::Method::Modifiers: 0
  Class::Method::Modifiers::Fast: 0
  Config::JFDI: 0
  DBD::SQLite: 1.31
  DBIx::Class: 0.08192
  DBIx::Class::Migration: 0
  DBIx::Class::Schema::Loader: 0.07010
  DateTime: 0
  DateTime::Format::DB2: 0
  DateTime::Format::DBI: 0
  DateTime::Format::MySQL: 0
  DateTime::Format::Pg: 0
  Directory::Scratch: 0
  File::Slurp: 9999.18
  File::chdir: 0
  Git::CPAN::Patch: 0
  Moo: 0
  MooX::Cmd: 0
  MooX::Types::MooseLike: 0
  MooseX::App::Cmd: 0
  MooseX::AutoDestruct: 0.007
  MooseX::RelatedClasses: 0
  MooseX::Types::Perl: 0
  Path::Class: 0
  Perl::Critic: 0
  Perl::Tidy: 0
  Pod::Cpandoc: 0
  Regexp::Debugger: 0
  Reindeer: 0.016
  Smart::Args: 0
  Smart::Comments: 0
  Sub::Exporter: 0
  Sub::Install: 0
  TAP::Harness::Restricted: 0
  Task::CPAN::Reporter: 0
  Test::Moose::More: 0.017
  Test::Routine: 0.015
  Test::TempDir: 0
  Try::Tiny: 0
  V: 0
  aliased: 0
  autobox::Colors: 0
  autobox::Core: 0
  autobox::JSON: 0
  autobox::dump: 0
  autodie: 2.22
  common::sense: 0
  lib::if::dev: 0
  local::lib: 0
  namespace::autoclean: 0
  opts: 0.05
  perl: 5.006
resources:
  bugtracker: https://github.com/RsrchBoy/task-belike-rsrchboy/issues
  homepage: http://metacpan.org/release/Task-BeLike-RSRCHBOY/
  repository: git://github.com/RsrchBoy/task-belike-rsrchboy.git
version: 0.005
x_Dist_Zilla:
  perl:
    version: 5.018001
  plugins:
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@RSRCHBOY/NextRelease'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: '@RSRCHBOY/Git::NextVersion'
      version: 2.019
    -
      class: Dist::Zilla::Plugin::ContributorsFromGit
      name: '@RSRCHBOY/ContributorsFromGit'
      version: 0.006
    -
      class: Dist::Zilla::Plugin::Git::CheckFor::CorrectBranch
      name: '@RSRCHBOY/@Git::CheckFor/Git::CheckFor::CorrectBranch'
      version: 0.008
    -
      class: Dist::Zilla::Plugin::Git::CheckFor::Fixups
      name: '@RSRCHBOY/@Git::CheckFor/Git::CheckFor::Fixups'
      version: 0.008
    -
      class: Dist::Zilla::Plugin::Git::CheckFor::MergeConflicts
      name: '@RSRCHBOY/@Git::CheckFor/Git::CheckFor::MergeConflicts'
      version: 0.008
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@RSRCHBOY/GatherDir'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::PromptIfStale
      config:
        Dist::Zilla::Plugin::PromptIfStale:
          check_all_plugins: 0
          check_all_prereqs: 0
          modules:
            - Dist::Zilla
            - Dist::Zilla::PluginBundle::RSRCHBOY
          phase: build
          skip: []
      name: '@RSRCHBOY/PromptIfStale'
      version: 0.014
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@RSRCHBOY/PruneCruft'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::Git::Describe
      name: '@RSRCHBOY/Git::Describe'
      version: 0.003
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@RSRCHBOY/ExecDir'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@RSRCHBOY/ShareDir'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@RSRCHBOY/MakeMaker'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::InstallGuide
      name: '@RSRCHBOY/InstallGuide'
      version: 1.200002
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@RSRCHBOY/Manifest'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::SurgicalPkgVersion
      name: '@RSRCHBOY/SurgicalPkgVersion'
      version: 0.0019
    -
      class: Dist::Zilla::Plugin::ReadmeFromPod
      name: '@RSRCHBOY/ReadmeFromPod'
      version: 0.21
    -
      class: Dist::Zilla::Plugin::MinimumPerl
      name: '@RSRCHBOY/MinimumPerl'
      version: 1.003
    -
      class: Dist::Zilla::Plugin::ReportVersions::Tiny
      name: '@RSRCHBOY/ReportVersions::Tiny'
      version: 1.10
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@RSRCHBOY/AutoPrereqs'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::Prepender
      name: '@RSRCHBOY/Prepender'
      version: 1.112280
    -
      class: Dist::Zilla::Plugin::Test::PodSpelling
      name: '@RSRCHBOY/Test::PodSpelling'
      version: 2.006001
    -
      class: Dist::Zilla::Plugin::ConsistentVersionTest
      name: '@RSRCHBOY/ConsistentVersionTest'
      version: 0.02
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@RSRCHBOY/PodCoverageTests'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@RSRCHBOY/PodSyntaxTests'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::NoTabsTests
      config:
        Dist::Zilla::Plugin::Test::NoTabs:
          module_finder:
            - ':InstallModules'
          script_finder:
            - ':ExecFiles'
      name: '@RSRCHBOY/NoTabsTests'
      version: 0.05
    -
      class: Dist::Zilla::Plugin::EOLTests
      name: '@RSRCHBOY/EOLTests'
      version: 0.02
    -
      class: Dist::Zilla::Plugin::HasVersionTests
      name: '@RSRCHBOY/HasVersionTests'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::Test::Compile
      config:
        Dist::Zilla::Plugin::Test::Compile:
          filename: t/00-compile.t
          module_finder:
            - ':InstallModules'
          script_finder:
            - ':ExecFiles'
      name: '@RSRCHBOY/Test::Compile'
      version: 2.039
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@RSRCHBOY/ExtraTests'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::NoSmartCommentsTests
      name: '@RSRCHBOY/NoSmartCommentsTests'
      version: 0.006
    -
      class: Dist::Zilla::Plugin::Test::Pod::LinkCheck
      name: '@RSRCHBOY/Test::Pod::LinkCheck'
      version: 1.001
    -
      class: Dist::Zilla::Plugin::Test::MinimumVersion
      name: '@RSRCHBOY/Test::MinimumVersion'
      version: 2.000005
    -
      class: Dist::Zilla::Plugin::Authority
      name: '@RSRCHBOY/Authority'
      version: 1.006
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@RSRCHBOY/MetaConfig'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@RSRCHBOY/MetaJSON'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@RSRCHBOY/MetaYAML'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::MetaNoIndex
      name: '@RSRCHBOY/MetaNoIndex'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: '@RSRCHBOY/MetaProvides::Package/AUTOVIV/:InstallModulesPM'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      config:
        Dist::Zilla::Plugin::MetaProvides::Package: {}
        Dist::Zilla::Role::MetaProvider::Provider:
          inherit_missing: 1
          inherit_version: 1
          meta_noindex: 1
      name: '@RSRCHBOY/MetaProvides::Package'
      version: 1.15000001
    -
      class: Dist::Zilla::Plugin::GitHub::Meta
      name: '@RSRCHBOY/GitHub::Meta'
      version: 0.36
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@RSRCHBOY/TestRelease'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::CheckChangesHasContent
      name: '@RSRCHBOY/CheckChangesHasContent'
      version: 0.006
    -
      class: Dist::Zilla::Plugin::CheckPrereqsIndexed
      name: '@RSRCHBOY/CheckPrereqsIndexed'
      version: 0.009
    -
      class: Dist::Zilla::Plugin::Git::Remote::Update
      name: '@RSRCHBOY/GitFetchOrigin'
      version: 0.1.2
    -
      class: Dist::Zilla::Plugin::Git::Remote::Check
      name: '@RSRCHBOY/GitCheckReleaseBranchSync'
      version: 0.1.2
    -
      class: Dist::Zilla::Plugin::Git::Remote::Check
      name: '@RSRCHBOY/GitCheckMasterBranchSync'
      version: 0.1.2
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@RSRCHBOY/Git::Check'
      version: 2.019
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@RSRCHBOY/Git::Commit'
      version: 2.019
    -
      class: Dist::Zilla::Plugin::Test::CheckDeps
      name: '@RSRCHBOY/Test::CheckDeps'
      version: 0.010
    -
      class: Dist::Zilla::Plugin::Travis::ConfigForReleaseBranch
      name: '@RSRCHBOY/Travis::ConfigForReleaseBranch'
      version: 0.001
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@RSRCHBOY/Git::Tag'
      version: 2.019
    -
      class: Dist::Zilla::Plugin::Git::CommitBuild
      name: '@RSRCHBOY/Git::CommitBuild'
      version: 2.019
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@RSRCHBOY/UploadToCPAN'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@RSRCHBOY/Git::Push'
      version: 2.019
    -
      class: Dist::Zilla::Plugin::Signature
      name: '@RSRCHBOY/Signature'
      version: 1.100930
    -
      class: Dist::Zilla::Plugin::InstallRelease
      name: '@RSRCHBOY/InstallRelease'
      version: 0.008
    -
      class: Dist::Zilla::Plugin::GitHub::Update
      name: '@RSRCHBOY/GitHub::Update'
      version: 0.36
    -
      class: Dist::Zilla::Plugin::ArchiveRelease
      name: '@RSRCHBOY/ArchiveRelease'
      version: 4.00
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@RSRCHBOY/ConfirmRelease'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::License
      name: '@RSRCHBOY/License'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::CPANFile
      name: '@RSRCHBOY/CPANFile'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::CopyFilesFromBuild
      name: '@RSRCHBOY/CopyFilesFromBuild'
      version: 0.103510
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: '@RSRCHBOY/ReadmeMarkdownInRoot'
      version: 0.133360
    -
      class: Dist::Zilla::Plugin::TaskWeaver
      name: '@RSRCHBOY/TaskWeaver'
      version: 0.101626
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 5.006
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 5.006
x_authority: cpan:RSRCHBOY
